version: "3.9"

services:
  db:
    image: postgres:17
    container_name: ds-lms-demo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ds-lms-demo
    ports:
      - "5432:5432"
    volumes:
      - ds-lms-demo-postgres-data:/var/lib/postgresql/data
      - ./prisma/seeder:/seeder:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ds-lms-demo-postgres-data:
